name: Deploy SNAPSHOT
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to use to deploy a SNAPSHOT from."
        required: true
        default: "main"
jobs:
  deploy:
    name: Deploy SNAPSHOT to Sonatype
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
        # only signed artifacts will be released to maven central. this sets up things for the maven-gpg-plugin
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase        
    - name: Run Maven Targets
      run: mvn --batch-mode --show-version --no-transfer-progress -DskipTests=true deploy --settings .maven-settings.xml --activate-profiles oss-release
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}

 