name: build

on: 
  pull_request:
  push:
    branches: 
      - main

jobs:
  test:
    name: Package and run all tests
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Run Maven Targets
      run: mvn package --batch-mode --show-version --no-transfer-progress
