name: build

on: 
  pull_request:
  push:
    branches: 
      - hive-4.x

jobs:
  test:
    name: Package and run all tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-package: 'jdk'
        java-version: '11'
        check-latest: true
    - name: Run Maven Targets
      run: mvn package --batch-mode --show-version --no-transfer-progress
