name: build

on: [push, pull_request]

jobs:
  test:
    name: Package and run all tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Init Coveralls
      shell: bash
      run: |
          COVERALLS_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }}
          if [[ -z "${COVERALLS_TOKEN}" ]];
          then
             echo "Coveralls token not available"
             COVERALLS_SKIP=true
          else
             echo "Coveralls token available"
             COVERALLS_SKIP=false
          fi
          echo ::set-env name=COVERALLS_SKIP::${COVERALLS_SKIP}
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Run Maven Targets
      run: mvn package
