name: Release to Maven Central
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to use to release from."
        required: true
        default: "hive-4.x"
jobs:
  release:
    name: Release to Maven Central
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.branch }}
        # We need a personal access token to be able to push to a protected branch
        token: ${{ secrets.HR_BOT_PERSONAL_ACCESS_TOKEN }}

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-package: 'jdk'
        java-version: '11'
        check-latest: true
        # this creates a settings.xml with the following server
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: SONATYPE_USERNAME # env variable for username in deploy
        server-password: SONATYPE_PASSWORD # env variable for token in deploy
        # only signed artifacts will be released to maven central. this sets up things for the GP
        gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
        cache: 'maven'

    - name: Configure Git User
      run: |
        git config user.email "hiverunnerproject@gmail.com"
        git config user.name "hiverunner-bot"

    - name: Run Maven Targets
      run: mvn release:prepare release:perform --activate-profiles oss-release --batch-mode --show-version --no-transfer-progress
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
